title: The "Very Clear" App.
description:  An easy to use cost comparision app for similar products at a grocery store.
tagline: An easy to use cost comparision app for similar products at a grocery store.
